In [ ]:
from pathlib import Path

import pandas as pd

In [ ]:
cwd = Path('.').resolve()
data_path = cwd / 'data'

In [ ]:
df = pd.read_pickle(data_path / 'allAssets_df.pkl')
df

,DAX Index,Eurostoxx 50 Index,FTSE 100 Index,S&P 500 Index,Nasdaq 100 Index,Nikkei 225 Index,Topix Index,KOSPI 200 Index,Hang Seng Index,EURUSD,...,UST 5Y,UST 10Y,UST Long,Euro Schatz,Euro Bobl,Euro Bund,Gilt 10Y,JGB 10Y,AGB 3Y,AGB 10Y
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,8768.903220,2443.196385,4663.410938,1110.469607,3472.256961,14612.63447,1183.492979,125.774501,10900.421630,84.7247,...,67.205578,56.429022,54.465692,94.644953,80.314443,70.939571,66.326959,101.388587,91.795922,91.597163
2000-01-04,8544.026504,2347.719768,4483.277751,1068.829363,3213.045685,14791.12124,1188.332027,127.696511,10671.302490,85.1545,...,67.431537,67.431537,54.920204,54.920204,94.663425,80.322243,70.829715,65.427993,91.628770,91.439483
2000-01-05,8417.734710,2292.443832,4391.038865,1070.154279,3172.402802,14251.78078,1131.646032,118.414606,9827.014147,85.3527,...,67.173303,67.173303,54.352064,54.352064,94.663425,80.314443,70.644332,65.011255,91.717262,91.557743
2000-01-06,8383.584378,2278.876102,4336.564450,1062.961874,2991.767767,13875.40650,1088.785889,113.633019,9393.884811,85.4018,...,67.291657,67.291657,54.787638,54.787638,94.672662,80.314443,70.548208,64.939814,91.628770,91.459193
2000-01-07,8801.764861,2353.749870,4365.973950,1105.169939,3217.109974,14077.17415,1103.994327,114.383072,9566.508822,85.1203,...,67.442294,67.442294,55.109584,55.109584,94.866625,80.696670,71.124953,65.231531,91.628770,91.478903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-05-31,15414.000000,4035.000000,7023.500000,4202.400000,13686.500000,28965.00000,1928.500000,427.700000,28958.000000,91.7084,...,124.414100,124.414100,158.125000,158.125000,112.045000,134.720000,169.940000,128.270000,99.785000,98.350000
2021-06-01,15567.000000,4070.000000,7078.000000,4198.600000,13648.750000,28760.00000,1920.000000,430.100000,29350.000000,91.6010,...,124.367200,124.367200,157.718800,157.718800,112.040000,134.710000,169.830000,127.890000,99.800000,98.370000
2021-06-02,15583.000000,4084.000000,7095.000000,4206.200000,13673.750000,28900.00000,1940.500000,429.500000,29144.000000,91.5835,...,124.421900,124.421900,158.093800,158.093800,112.050000,134.820000,170.150000,128.200000,99.800000,98.380000
2021-06-03,15651.000000,4086.000000,7068.500000,4191.300000,13529.250000,29030.00000,1959.000000,433.450000,28858.000000,90.9510,...,124.203100,124.203100,157.656300,157.656300,112.045000,134.800000,169.940000,127.890000,99.805000,98.395000
2021-06-04,15641.000000,4080.000000,7062.500000,4192.500000,13519.750000,28950.00000,1954.000000,432.149994,28792.000000,91.2485,...,124.218750,124.218750,157.656250,157.656250,112.050003,134.800003,169.869995,127.890000,99.785004,98.375000

In [ ]:
df.columns

Index(['DAX Index', 'Eurostoxx 50 Index', 'FTSE 100 Index', 'S&P 500 Index',
       'Nasdaq 100 Index', 'Nikkei 225 Index', 'Topix Index',
       'KOSPI 200 Index', 'Hang Seng Index', 'EURUSD', 'GBPUSD', 'SEKUSD',
       'CADUSD', 'JPYUSD', 'AUDUSD', 'NZDUSD', 'USDKRW', 'Brent Crude',
       'WTI Crude', 'Heating Oil', 'Natural Gas', 'Gold', 'Silver', 'Copper',
       'Corn', 'Soybean', 'Eurodollar', 'UST 2Y', 'UST 5Y', 'UST 10Y',
       'UST Long', 'Euro Schatz', 'Euro Bobl', 'Euro Bund', 'Gilt 10Y',
       'JGB 10Y', 'AGB 3Y', 'AGB 10Y'],
      dtype='object')

In [ ]:
assets = list(df.columns)
assetclasses = ['E', 'F', 'C', 'B'] # E: 'equity', F: 'fx', C: 'commodity', B: 'bond'

assetclass2asset = {
    'E': assets[0:9],
    'F': assets[9:17],
    'C': assets[17:26],
    'B': assets[26:]
}

In [ ]:
asset2assetclass = {}

for asstcls, assts in assetclass2asset.items():
    for asst in assts:
        asset2assetclass[asst] = asstcls

In [ ]:
def asset2code(asset):
    assetclass = asset2assetclass[asset]
    assetindex = assets.index(asset)

    return assetclass + str(assetindex)

In [ ]:
df.columns = [asset2code(col) for col in df.columns]

In [ ]:
df.to_pickle(data_path / 'crossasset.pkl')